heat_template_version: 2016-10-14

description: Linux Web_Server
 
parameters:

  password:
    type: string
    label: Root Password
    description: root/admin password
    default: Passw0rd
    hidden: true

resources:

  network0:
    type: OS::Neutron::Net
    properties:
      name: network0
      admin_state_up: true
         
      
  subnet0:
    type: OS::Neutron::Subnet
    properties:
      allocation_pools:
        - end: 10.0.1.253
          start: 10.0.1.200
      cidr: 10.0.1.0/24
      gateway_ip: 10.0.1.254
      dns_nameservers: [10.50.255.254]
      enable_dhcp: false
      name: subnet0
      network_id:
        get_resource: network0
        
  external-router:
    type: OS::Neutron::Router    
    properties:
      name: external-router
      external_gateway_info: 
        network: public
        
  external-router-interface:
    type:  OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: external-router }       
      subnet_id: { get_resource: subnet0 }
      
  floatingIP-port:
    type: OS::Neutron::Port
    properties:
      name: floatingIP-port
      network_id: { get_resource: network0 }
      security_groups:
        - get_resource: Security_Group
      fixed_ips:
        - subnet_id: { get_resource: subnet0 }
          ip_address: 10.0.1.205
          
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public
      
  floating_ip_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_resource: floatingIP-port }
      
  Security_Group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: Security_Group
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
        - remote_ip_prefix: 10.0.0.0/11
          protocol: tcp
          direction: ingress
          port_range_min: 1
          port_range_max: 65535
        - remote_ip_prefix: 10.32.0.0/12
          protocol: tcp
          direction: ingress
          port_range_min: 1
          port_range_max: 65535
        - remote_ip_prefix: 10.48.0.0/15
          protocol: tcp
          direction: ingress
          port_range_min: 1
          port_range_max: 65535
        - remote_ip_prefix: 10.50.0.0/20
          protocol: tcp
          direction: ingress
          port_range_min: 1
          port_range_max: 65535
        - remote_ip_prefix: 10.50.16.0/22
          protocol: tcp
          direction: ingress
          port_range_min: 1
          port_range_max: 65535
        - remote_ip_prefix: 192.168.0.0/13
          protocol: tcp
          direction: ingress
          port_range_min: 1
          port_range_max: 65535
        - remote_ip_prefix: 192.176.0.0/12
          protocol: tcp
          direction: ingress
          port_range_min: 1
          port_range_max: 65535
        - remote_ip_prefix: 192.192.0.0/14
          protocol: tcp
          direction: ingress
          port_range_min: 1
          port_range_max: 65535
        - remote_ip_prefix: 192.196.0.0/17
          protocol: tcp
          direction: ingress
          port_range_min: 1
          port_range_max: 65535
        - remote_ip_prefix: 192.196.128.0/18
          protocol: tcp
          direction: ingress
          port_range_min: 1
          port_range_max: 65535
        - remote_ip_prefix: 192.196.192.0/19
          protocol: tcp
          direction: ingress
          port_range_min: 1
          port_range_max: 65535
        - remote_ip_prefix: 192.196.224.0/20
          protocol: tcp
          direction: ingress
          port_range_min: 1
          port_range_max: 65535
        - remote_ip_prefix: 10.0.1.205
          #port_range_min: 1
          #port_range_max: 65535
          
  host1:
    type: OS::Nova::Server
    properties:
      name: Linux Web Server
      image: Debian LXDE
      flavor: cy.medium
      networks: 
        - port: { get_resource: floatingIP-port }
      user_data: 
        str_replace:
          template: |
            #!/bin/bash
            echo 127.0.0.1 $(hostname) >> /etc/hosts
            echo 173.230.138.130 git.cybbh.space >> /etc/host
            useradd -m -G sudo zeus
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt-get -y install locate dnsutils lsof aptitude ftp auditd telnet samba git zip unzip figlet hexedit tree qemu apache2 gcc tcc
            apt-get upgrade
            updatedb
            mandb
            mkdir /var/www/html/linux
            wget goo.gl/eGEfnd -O /var/www/html/linux/banner.sh
            wget goo.gl/pZN4ED -O /var/www/html/linux/check.pyc
            wget goo.gl/KwvVVC -O /var/www/html/linux/runme
            wget goo.gl/yhFrdp -O /var/www/html/linux/page.html
            wget goo.gl/DdLP6a -O /var/www/html/linux/fun.zip
            wget goo.gl/Uggv6h -O /var/www/html/linux/mbroken.zip
            wget goo.gl/g9JJ9z -O /var/www/html/linux/mbrgood.zip
            wget goo.gl/FEAeHi -O /var/www/html/linux/NMAP_all_hosts.txt
            wget goo.gl/NVG6Gu -O /var/www/html/linux/LEMARCHAND.zip
            wget goo.gl/kyDrPg -O /var/www/html/linux/sorted.zip
            mkdir /rootkits
            git clone https://github.com/D4NP0UL1N/0010100010.git /rootkits
            echo 0 > /proc/sys/kernel/randomize_va_space
            gcc -o /var/www/html/linux/sudo_bad /rootkits/sudo.c 2>/dev/null
            zip /var/www/html/linux/rootkits.zip /rootkits/*
            chmod +x /var/www/html/linux/*
            service apache2 start
            bash
            #User accounts
            sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
            echo "zeus:$password" | chpasswd
            echo "root:$password" | chpasswd
            reboot
          params:
            $password: { get_param: password }
      user_data_format: RAW
